### PR TITLE
Add btn back to top

### LINKED ISSUE #314: Add button back to top

### PR DESCRIPTION
**Pull request by danichim**
### Requirements for making a pull request

Thank you for contributing to our project! 

Please fill out the template below to help the project maintainers review it as fast as possible and include your contribution to the project.

### What does it fix?

Closes #314 

Update FE components to use version 1.0.10 and add the back to top button

### How has it been tested?

Please describe the tests that you ran to verify your changes.

Scroll and click on back to top button

### CODE REVIEW

**Comment by catileptic** [comment]
I checked this feature in the now.sh preview and I also ran this code locally and I don't see the button anywhere. @danichim can you double-check that it works as you intended?

**Comment by danichim** [comment]
> I checked this feature in the now.sh preview and I also ran this code locally and I don't see the button anywhere. @danichim can you double-check that it works as you intended?

image

**Comment by catileptic** [comment]
It seems like this feature works on Chrome and Firefox, but not in Safari (not on the desktop version, nor the mobile version). @danichim can you please test this on Safari and make it work across all browsers?

Additionally, the button should not appear when the user can see the very top of the page. It should only appear when the user scrolls down and can't see the header anymore. 

When the user is at the bottom of the page, the button is placed in the footer area. Can we make it so that the button is not pushed into the footer, and rests just above it?

**Comment by danichim** [comment]
> It seems like this feature works on Chrome and Firefox, but not in Safari (not on the desktop version, nor the mobile version). @danichim can you please test this on Safari and make it work across all browsers?
> 
> Additionally, the button should not appear when the user can see the very top of the page. It should only appear when the user scrolls down and can't see the header anymore.
> 
> When the user is at the bottom of the page, the button is placed in the footer area. Can we make it so that the button is not pushed into the footer, and rests just above it?

I checked in safari and it works.
image

**Comment by catileptic** [comment]
Closing this as per #314

**Pull request closed without merging**
