### PR TITLE
Fix legend on cases/day graph

### LINKED ISSUE #361: Graph crashes if disabling one graph and then hover the graph
On the "Număr de cazuri pe zile" graph, if you disable one of the graphs by clicking on the legend of the graph, and then hover the graph, the graph will cease to work.

### PR DESCRIPTION
**Pull request by Utwo**
Closes #361

### CODE REVIEW

**Comment by web-sys1** [comment]
Sorry @catileptic, but the problem is far to be resolved.
screenshot-1596626342861

Also, got error message when opened DevTools > Console in Chrome Browser:

```
TypeError: Cannot read property 'seriesName' of undefined
    at formatter (main.845387c9.chunk.js?__WB_REVISION__=eb503ea4e7511eb64dcc:1)
    at n._showTooltipContent (TooltipView.js:543)
    at n.<anonymous> (TooltipView.js:437)
    at util.js:426
    at n._showOrMove (TooltipView.js:355)
    at n._showAxisTooltip (TooltipView.js:433)
    at n._tryShow (TooltipView.js:330)
    at n.manuallyShowTip (TooltipView.js:229)
    at c (echarts.js:1039)
    at V.<anonymous> (echarts.js:1034)
```

**Comment by Utwo** [comment]
> Sorry @catileptic, but the problem is far to be resolved.
> screenshot-1596626342861
> 
> Also, got error message when I've opened `DevTools` > `Console` in Chrome browser:
> 
> ```
> TypeError: Cannot read property 'seriesName' of undefined
>     at formatter (main.845387c9.chunk.js?__WB_REVISION__=eb503ea4e7511eb64dcc:1)
>     at n._showTooltipContent (TooltipView.js:543)
>     at n.<anonymous> (TooltipView.js:437)
>     at util.js:426
>     at n._showOrMove (TooltipView.js:355)
>     at n._showAxisTooltip (TooltipView.js:433)
>     at n._tryShow (TooltipView.js:330)
>     at n.manuallyShowTip (TooltipView.js:229)
>     at c (echarts.js:1039)
>     at V.<anonymous> (echarts.js:1034)
> ```

Hello, please test the following URL: https://date-la-zi-git-fork-utwo-fix-case-day-legend.code4romania.vercel.app/

**Comment by surdu** [comment]
@web-sys1 the fix is not published yet.

**Comment by web-sys1** [comment]
@surdu Worked well. It takes a while to be published on website.
screen1596632242838-anim

**Comment by web-sys1** [comment]
Also, I requested adding processed tests graph (see #349)

**Pull request merged**
