### PR TITLE
Per day table

### PR DESCRIPTION
**Pull request by chalx**
### Requirements for making a pull request

Thank you for contributing to our project! 

Please fill out the template below to help the project maintainers review it as fast as possible and include your contribution to the project.

### What does it fix?

Closes https://github.com/code4romania/date-la-zi/issues/245

Add per day table.

### How has it been tested?

image

### CODE REVIEW

**Comment by madpipeline** [comment]
@chalx please rebase your branch, to pull in the CI fixes.

**Comment by chalx** [comment]
@dependabot rebase

**Comment by madpipeline** [comment]
It's another CI issue. I'm working on it. It's caused by the GHA workflow getting triggered from a forked repo.

**Comment by chalx** [comment]
@madpipeline exact, problema este ca cauta acele secrete la mine pe proiect si anumite drepturi eu nu le am, de asta pica

**Comment by madpipeline** [comment]
Issue is fixed. Please rebase again.

**Comment by CristiHabliuc** [comment]
@chalx can you rebase again and we can see if it's fixed?

**Comment by chalx** [comment]
Am adaugat si paginare

image

**Comment by CristiHabliuc** [comment]
Awesome taking a look ASAP

**Comment by chalx** [comment]
@CristiHabliuc please take a look

- [x] The list is not sorted by day
- [x] The card's height should be kept fixed once it's computed (going to next page shouldn't affect height if there are less records)

**Comment by chalx** [comment]
@CristiHabliuc done

**Pull request merged**
